events:
  - name: "Example event"
    key: "example_event"
    patterns:
      - key: _contract_address
        value: "address"
      - key: action
        value: "example"
      - key: sender
        value: "address"